spring.application.name=todo-api
# Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Garante que o script rode em bancos de dados reais (como MySQL) e não só em memória
spring.sql.init.mode=always

# Se você quer que o Hibernate crie as tabelas antes do script rodar
spring.jpa.defer-datasource-initialization=true

# Caminho para acessar a interface visual
springdoc.swagger-ui.path=/swagger-ui.html

# Caminho para o JSON da documentação (usado por ferramentas externas)
springdoc.api-docs.path=/api-docs

# Ordena os endpoints por método HTTP (GET, POST, etc)
springdoc.swagger-ui.operationsSorter=method

api.security.token.secret=${API_SECURITY_TOKEN_SECRET}